const { default: makeWASocket, useMultiFileAuthState, fetchLatestBaileysVersion, downloadMediaMessage } = require("@itsukichan/baileys")
const P = require("pino")
const fs = require("fs");
const { exec } = require("child_process");
const PREFIX = '.'; const BOT = 'nicobot'; const OWNER = '393887347002'; const MONETA = 'schei'; const DB_FILE = './nicoschei.json'; const SOLO_FILE = './soloadmin.json'; const AVVIO = Date.now();
function db() { try { return JSON.parse(fs.readFileSync(DB_FILE, "utf8")); } catch (e) { return {}; } }
function saveDB(d) { fs.writeFileSync(DB_FILE, JSON.stringify(d, null, 2)); }
function getSaldo(jid) { return db()[jid] || 0; }
function addSaldo(jid, n) { const d = db(); d[jid] = Math.max(0, (d[jid] || 0) + n); saveDB(d); return d[jid]; }
function soloDB() { try { return JSON.parse(fs.readFileSync(SOLO_FILE, "utf8")); } catch (e) { return {}; } }
function soloSave(d) { fs.writeFileSync(SOLO_FILE, JSON.stringify(d, null, 2)); }
function isSoloOn(jid) { return!!soloDB()[jid]; }
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const at = (jid) => "@" + String(jid).split("@")[0];
function uptime() { let s = Math.floor((Date.now() - AVVIO) / 1000); const h = Math.floor(s / 3600), mn = Math.floor((s % 3600) / 60); return h? h + "h " + mn + "m" : mn + "m " + (s % 60) + "s"; }
function calc(expr) { if (!/^[-+*/().\d\s%]+$/.test(expr || "")) return "espressione non valida"; try { const r = Function("return (" + expr + ")")(); return (typeof r === "number" && isFinite(r))? r : "espressione non valida"; } catch (e) { return "espressione non valida"; } }
function F(testo, V) { return String(testo == null? "" : testo).replace(/\{(\w+)\}/g, (x, k) => (V[k]!== undefined? V[k] : x)); }
function corpo(m) { const t = m.message || {}; return t.conversation || (t.extendedTextMessage && t.extendedTextMessage.text) || (t.imageMessage && t.imageMessage.caption) || (t.buttonsResponseMessage && t.buttonsResponseMessage.selectedButtonId) || (t.templateButtonReplyMessage && t.templateButtonReplyMessage.selectedId) || ""; }
function menzionati(m) { const e = m.message && m.message.extendedTextMessage && m.message.extendedTextMessage.contextInfo; if (e && e.mentionedJid && e.mentionedJid.length) return e.mentionedJid[0]; if (e && e.participant) return e.participant; return null; }
const TMP = "./tmp"; if (!fs.existsSync(TMP)) fs.mkdirSync(TMP);
function sh(cmd) { return new Promise((ok, ko) => { exec(cmd, { maxBuffer: 1024 * 1024 * 40, timeout: 120000 }, (e, so, se) => { if (e) ko(new Error((se || e.message).split("\n").slice(-3).join(" ").slice(0, 160))); else ok(so); }); }); }
function pulisci(files) { for (const f of files) { try { fs.unlinkSync(f); } catch (e) {} } }
async function prendiMedia(m) { const ctx = m.message && m.message.extendedTextMessage && m.message.extendedTextMessage.contextInfo; const q = ctx && ctx.quotedMessage; const msg = q? { key: m.key, message: q } : m; const tipi = Object.keys(msg.message || {}); const img = tipi.includes("imageMessage"); const vid = tipi.includes("videoMessage"); const stk = tipi.includes("stickerMessage"); if (!img &&!vid &&!stk) return null; try { const buffer = await downloadMediaMessage(msg, "buffer", {}); return { buffer, video: vid, sticker: stk, immagine: img }; } catch (e) { return null; } }
const GIORNI = ["domenica", "lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato"];
const MESI = ["gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno","luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"];
function makeV(extra) { const n = new Date(); return Object.assign({ user: "", id: "", tag: "", nome: "utente", chat: "", gruppo: "chat privata", descr: "", membri: 1, admin: "no", owner: "no", isgruppo: "no", saldo: 0, saldotarget: 0, prefix: PREFIX, bot: BOT, moneta: MONETA, cmd: "", args: "", arg1: "", arg2: "", arg3: "", target: "nessuno", targetnome: "nessuno", citato: "", tipo: "testo", ora: n.toTimeString().slice(0, 5), orario: n.toTimeString().slice(0, 8), data: n.toLocaleDateString("it-IT"), giorno: GIORNI[n.getDay()], mese: MESI[n.getMonth()], anno: n.getFullYear(), random: Math.floor(Math.random() * 100) + 1, dado: Math.floor(Math.random() * 6) + 1, ping: 0, uptime: uptime(), ram: Math.round(process.memoryUsage().rss / 1048576) + "MB", node: process.version, totcmd: 0, risultato: "" }, extra || {}); }
const BLOCCHI = [
{ tipo: 'comando', desc: 'Lista dei comandi', nomi: ['menu', 'help', 'comandi', 'm'], async run(ctx) { const { reply, V } = ctx; V.totcmd = BLOCCHI.filter(b=>b.tipo==="comando").length; let testo = F('╭─ *NICOBOT* ─────\n│ {totcmd} comandi · prefisso {prefix}\n│ attivo da {uptime}\n╰──────────────', V); for (const b of BLOCCHI) { if (b.tipo!== "comando") continue; testo += "\n" + PREFIX + b.nomi[0] + (b.desc? " · " + b.desc : ""); } await reply(testo); }},
{ tipo: 'comando', desc: 'Test di vita', nomi: ['ping', 'p'], async run(ctx) { const { reply, V, t0 } = ctx; V.ping = Date.now() - t0; V.uptime = uptime(); await reply(F('🏓 *{ping}ms*\n⚙ {ram} · Node {node}\n⏱ attivo da {uptime}', V)); }},
{ tipo: 'comando', desc: 'Pannello di stato', nomi: ['sicurezza', 'stato', 'status'], async run(ctx) { const { reply, V, t0 } = ctx; V.ping = Date.now() - t0; V.uptime = uptime(); await reply(F('╭─ *STATO NICOBOT*\n│ 🟢 online da {uptime}\n│ 🏓 latenza {ping}ms\n│ 🧠 memoria {ram}\n│ 📦 Node {node}\n│ 🧩 {totcmd} comandi caricati\n│ 👥 chat: {gruppo} ({membri})\n│ 🕒 {orario} · {giorno} {data}\n╰──────────────', V)); }},
{ tipo: 'comando', desc: 'Quanto hai in cassa', nomi: ['saldo', 'bal', 'soldi', 'money'], async run(ctx) { const { reply, V, sender } = ctx; V.saldo = getSaldo(sender); await reply(F('💰 *{nome}*\nSaldo: *{saldo}* {moneta}', V)); }},
{ tipo: 'comando', desc: 'Guadagna monete', nomi: ['lavora', 'work'], async run(ctx) { const { reply, V, sender } = ctx; await reply(F('⛏ {nome} si mette al lavoro…', V)); await sleep(1200); const n = parseInt(V.arg1, 10); const amount = isNaN(n)? 250 : n; addSaldo(sender, amount); V.saldo = getSaldo(sender); V.arg1 = amount; await reply(F('✅ Hai guadagnato *{arg1}* {moneta}.\nTotale: *{saldo}*', V)); }},
{ tipo: 'comando', desc: 'Attiva comandi solo per admin', nomi: ['attivasoloadmin', 'soloadminon', 'soloon'], soloGruppo: true, soloAdmin: true, async run(ctx) { const { from, reply } = ctx; const d = soloDB(); d[from] = true; soloSave(d); await reply(`🔒 *SOLO-ADMIN ATTIVATO*\nOra solo gli admin possono usare i comandi.\nPer disattivare:.disattivasoloadmin`); }},
{ tipo: 'comando', desc: 'Disattiva comandi solo per admin', nomi: ['disattivasoloadmin', 'soloadminoff', 'solooff'], soloGruppo: true, soloAdmin: true, async run(ctx) { const { from, reply } = ctx; const d = soloDB(); delete d[from]; soloSave(d); await reply(`🔓 *SOLO-ADMIN DISATTIVATO*\nOra tutti possono usare i comandi.`); }},
{ tipo: 'comando', desc: 'Tira un dado', nomi: ['dado', 'rolla'], async run(ctx) { const { reply, V } = ctx; await reply(F('🎲 {nome} tira il dado… esce *{dado}*!', V)); }},
{ tipo: 'comando', desc: 'Calcolatrice', nomi: ['calc', 'math', 'matematica'], async run(ctx) { const { reply, V } = ctx; V.risultato = calc(V.args); await reply(F('🧮 {args} = *{risultato}*', V)); }},
{ tipo: 'comando', desc: 'Immagine o video in sticker', nomi: ['sticker', 's', 'stiker'], async run(ctx) { const { sock, m, from, reply, V } = ctx; const md = await prendiMedia(m); if (!md) { await reply("Manda o cita un'immagine / video con questo comando."); } else { const inF = TMP + "/in" + Date.now(), outF = TMP + "/st" + Date.now() + ".webp"; fs.writeFileSync(inF, md.buffer); const filtro = "scale=512:512:force_original_aspect_ratio=decrease,fps=15,pad=512:512:-1:-1:color=#00000000"; const extra = md.video? "-t 7 -loop 0 -an -preset default" : ""; try { await sh("ffmpeg -y -i " + inF + " -vf \"" + filtro + "\" " + extra + " -c:v libwebp -q:v 60 " + outF); await sock.sendMessage(from, { sticker: fs.readFileSync(outF) }, { quoted: m }); } catch (e) { await reply("ffmpeg non ce l'ha fatta: " + e.message); } pulisci([inF, outF]); } }},
{ tipo: 'comando', desc: 'Solo admin possono scrivere', nomi: ['muta', 'mute', 'chiudi'], soloGruppo: true, soloAdmin: true, async run(ctx) { const { sock, from, reply, V } = ctx; await sock.groupSettingUpdate(from, 'announcement'); await reply(F('🔇 *Gruppo chiuso* da {nome}.\nSolo gli admin possono scrivere.', V)); }},
{ tipo: 'comando', desc: 'Riapre il gruppo a tutti', nomi: ['smuta', 'unmute', 'apri'], soloGruppo: true, soloAdmin: true, async run(ctx) { const { sock, from, reply, V } = ctx; await sock.groupSettingUpdate(from, 'not_announcement'); await reply(F('🔊 *Gruppo riaperto* da {nome}.\nPotete scrivere tutti.', V)); }},
{ tipo: 'comando', desc: 'Tagga tutto il gruppo', nomi: ['tagall', 'everyone', 'all'], soloGruppo: true, soloAdmin: true, async run(ctx) { const { sock, from, V, at } = ctx; const mem = (await sock.groupMetadata(from)).participants.map(x => x.id); await sock.sendMessage(from, { text: F('📢 *Avviso da {nome}*\n{args}', V) + "\n" + mem.map(at).join(" "), mentions: mem }); }},
{ tipo: 'comando', desc: 'Butta fuori chi tagghi', nomi: ['kick', 'ban', 'rimuovi'], soloGruppo: true, soloAdmin: true, async run(ctx) { const { sock, from, target, reply, V } = ctx; await reply(F('🚪 {target} rimosso da {nome}.', V)); if (target) await sock.groupParticipantsUpdate(from, [target], "remove"); }},
];

async function onMessage(sock, m) {
  try {
    if (!m ||!m.message || m.key.fromMe) return;
    const t0 = Date.now(); const from = m.key.remoteJid; const isGroup = from.endsWith("@g.us");
